In [1]:
import pandas as pd
import numpy as np
import datetime
import json
import os
from IPython.display import display_html
from IPython.display import HTML

In [2]:
def display_horizontal(*args):
    html_str = ''
    for df in args:
        html_str += df.to_html()
    display_html(
        html_str.replace('table','table style="display:inline;margin-right:50px"'), 
        raw=True
    )

In [3]:
with open("INDEX_START.json", "r", encoding="utf-8") as f:
    INDEX_START = json.load(f)
    
with open("INDEX_NAME.json", 'r', encoding = 'utf-8') as f:
    INDEX_NAME = json.load(f)

In [13]:
INDEX_DATA = {}

for ticker in INDEX_START:
    path = f"Data/{ticker}.csv"
    
    if os.path.isfile(path): 
        data = pd.read_csv(path, index_col = 0, parse_dates = True)
        data.index = pd.to_datetime(data.index, format="%Y-%m-%d", errors='coerce')
        data.index = data.index.date
        INDEX_DATA[ticker] = data.copy(deep = True)

In [14]:
UNIVERSE = {}
target_dates = {}
today_date = datetime.datetime(2025, 2, 21)

for ticker in INDEX_DATA:
    target_dates[ticker] = INDEX_DATA[ticker].index[-1]

UNIVERSE = INDEX_DATA

In [15]:
print(f"Assets under Analysis: {len(UNIVERSE)}")
print(f"Total Assets: {len(INDEX_DATA)}")

Assets under Analysis: 69
Total Assets: 69

## Z Score Calculation

In [16]:
Z_PE_TTM = {}
Z_DIVIDENDYIELD = {}
years = 5
duration = years * 250

for ticker in UNIVERSE:
    target_date = target_dates[ticker]
    if len(UNIVERSE[ticker]) < duration:
        continue
    
    # PE TTM 分位值
    sample_data = UNIVERSE[ticker]['PE_TTM'].loc[:target_date].iloc[-duration:]
    assert len(sample_data) == duration
    
    mean = sample_data.mean()
    std = sample_data.std()
    
    Z = (UNIVERSE[ticker].loc[target_date, "PE_TTM"] - mean) / std
    
    Z_PE_TTM[ticker] = Z
    
    
    # 股息率 分位值
    sample_data = UNIVERSE[ticker]['DIVIDENDYIELD2'].loc[:target_date].iloc[-duration:]
    assert len(sample_data) == duration
    
    mean = sample_data.mean()
    std = sample_data.std()
    
    Z = (UNIVERSE[ticker].loc[target_date, 'DIVIDENDYIELD2'] - mean) / std
    
    Z_DIVIDENDYIELD[ticker] = Z

In [17]:
display_number = 20

df_Z_PE_TTM = pd.DataFrame(list(Z_PE_TTM.items()), columns=['Ticker', '市盈率'])
df_Z_DIVIDENDYIELD = pd.DataFrame(list(Z_DIVIDENDYIELD.items()), columns=['Ticker', '股息率'])

# Sort the dataframes
df_Z_PE_TTM_sorted = df_Z_PE_TTM.sort_values(by='市盈率', ascending=True)
df_Z_DIVIDENDYIELD_sorted = df_Z_DIVIDENDYIELD.sort_values(by='股息率', ascending=False)

# Display the top 10 sorted rows
top_Z_PE_TTM = df_Z_PE_TTM_sorted.head(display_number).copy()
top_Z_DIVIDENDYIELD = df_Z_DIVIDENDYIELD_sorted.head(display_number).copy()

top_Z_PE_TTM.loc[:, "指数名称"] = top_Z_PE_TTM["Ticker"].map(INDEX_NAME)
top_Z_PE_TTM = top_Z_PE_TTM[["Ticker", "指数名称", "市盈率"]]

top_Z_DIVIDENDYIELD.loc[:, "指数名称"] = top_Z_DIVIDENDYIELD["Ticker"].map(INDEX_NAME)
top_Z_DIVIDENDYIELD = top_Z_DIVIDENDYIELD[["Ticker", "指数名称", "股息率"]]

In [18]:
print()
print(f"{INDEX_DATA['000300.SH'].index[-1].strftime('%Y-%m-%d')}")
print(f"{years}年")
display_horizontal(top_Z_PE_TTM, top_Z_DIVIDENDYIELD)
print()

2025-04-01
5年

,Ticker,指数名称,市盈率
15,931787CNY00.CSI,港股创新药,-1.247287
16,H30533.CSI,中概互联网,-1.190553
17,HSIII.HI,恒生互联网,-1.101265
31,707717L.MI,MSCI中国A股质量,-1.033177
2,000913.SH,医药,-0.926117
11,601688.SH,华泰证券,-0.817824
35,HSCGSI.HI,恒生消费,-0.773177
3,399814.SZ,农业,-0.746572
41,HSHK35.HI,恒生香港35,-0.709653
29,HSSCHI.HI,恒生港股通医疗,-0.651907
9,N225.GI,日经,-0.647545
26,704843.MI,MSCI中国A股国际,-0.505383
37,HSSCNE.HI,恒生新经济,-0.463118
27,133333.CSI,MSCI中国A股,-0.427353
14,FCHI.GI,法国CAC40,-0.393779
24,718711L.MI,MSCI中国A股人民币,-0.384125
25,716567.MI,MSCI中国A股国际(美元),-0.384020
52,716567.CSI,MSCI中国A国际实时,-0.384020
21,HSHCI.HI,恒生医疗保健,-0.383502
46,CES100.CSI,中华港股100,-0.355348
,Ticker,指数名称,股息率
23,707918.MI,MSCI中国A股低波(美元),2.016232
2,000913.SH,医药,1.998827
21,HSHCI.HI,恒生医疗保健,1.926889
26,704843.MI,MSCI中国A股国际,1.867388
25,716567.MI,MSCI中国A股国际(美元),1.833010
52,716567.CSI,MSCI中国A国际实时,1.833010
24,718711L.MI,MSCI中国A股人民币,1.832966
4,000300.SH,沪深300,1.784543
28,HSCAIT.HI,恒生A股龙头,1.659365
27,133333.CSI,MSCI中国A股,1.651119
3,399814.SZ,农业,1.563189
31,707717L.MI,MSCI中国A股质量,1.557423
30,DJCN88.GI,道中88,1.479261
8,830009.XI,富时中国A50,1.478203
11,601688.SH,华泰证券,1.187175
32,302400.MI,MSCI中国(美元),1.149174
34,CES300.CSI,中华沪深港300,1.093215
20,122489.MI,MSCI金龙,1.051439
35,HSCGSI.HI,恒生消费,1.010628
41,HSHK35.HI,恒生香港35,0.980751

In [20]:
durations = [3, 5]

for years in durations:
    Z_PE_TTM = {}
    Z_DIVIDENDYIELD = {}
    target_date = INDEX_DATA['000300.SH'].index[-1]
    duration = years * 250

    for ticker in UNIVERSE:
        if len(UNIVERSE[ticker]) < duration:
            continue
    
        sample_data = UNIVERSE[ticker]['PE_TTM'].loc[:target_date].iloc[-duration:]
        assert len(sample_data) == duration
    
        mean = sample_data.mean()
        std = sample_data.std()
    
        Z = (UNIVERSE[ticker].loc[target_date, "PE_TTM"] - mean) / std

        if std == 0:
            print(ticker, duration, len(sample_data))
    
        Z_PE_TTM[ticker] = Z
    
    
        sample_data = UNIVERSE[ticker]['DIVIDENDYIELD2'].loc[:target_date].iloc[-duration:]
        assert len(sample_data) == duration
    
        mean = sample_data.mean()
        std = sample_data.std()
    
        Z = (UNIVERSE[ticker].loc[target_date, 'DIVIDENDYIELD2'] - mean) / std
    
        Z_DIVIDENDYIELD[ticker] = Z


    display_number = 20

    df_Z_PE_TTM = pd.DataFrame(list(Z_PE_TTM.items()), columns=['Ticker', '市盈率'])
    df_Z_DIVIDENDYIELD = pd.DataFrame(list(Z_DIVIDENDYIELD.items()), columns=['Ticker', '股息率'])

    # Sort the dataframes
    df_Z_PE_TTM_sorted = df_Z_PE_TTM.sort_values(by='市盈率', ascending=True)
    df_Z_DIVIDENDYIELD_sorted = df_Z_DIVIDENDYIELD.sort_values(by='股息率', ascending=False)

    # Display the top 10 sorted rows
    top_Z_PE_TTM = df_Z_PE_TTM_sorted.head(display_number).copy()
    top_Z_DIVIDENDYIELD = df_Z_DIVIDENDYIELD_sorted.head(display_number).copy()

    top_Z_PE_TTM.loc[:, "指数名称"] = top_Z_PE_TTM["Ticker"].map(INDEX_NAME)
    top_Z_PE_TTM = top_Z_PE_TTM[["Ticker", "指数名称", "市盈率"]]

    top_Z_DIVIDENDYIELD.loc[:, "指数名称"] = top_Z_DIVIDENDYIELD["Ticker"].map(INDEX_NAME)
    top_Z_DIVIDENDYIELD = top_Z_DIVIDENDYIELD[["Ticker", "指数名称", "股息率"]]


    print()
    print(f"{INDEX_DATA['000300.SH'].index[-1].strftime('%Y-%m-%d')}")
    print(f"{years}年")
    display_horizontal(top_Z_PE_TTM, top_Z_DIVIDENDYIELD)
    print()

KeyError: datetime.date(2025, 4, 1)

In [111]:
target_dates

{'NDX.GI': Timestamp('2025-02-21 00:00:00'),
 'SPX.GI': Timestamp('2025-02-21 00:00:00'),
 '000913.SH': Timestamp('2025-02-21 00:00:00'),
 '399814.SZ': Timestamp('2025-02-21 00:00:00'),
 '000300.SH': Timestamp('2025-02-21 00:00:00'),
 'HSI.HI': Timestamp('2025-02-21 00:00:00'),
 'HSTECH.HI': Timestamp('2025-02-21 00:00:00'),
 'NDXTMC.GI': Timestamp('2025-02-21 00:00:00'),
 'GDAXI.GI': Timestamp('2025-02-19 00:00:00'),
 'CSPSADRP.CI': Timestamp('2025-02-21 00:00:00'),
 '830009.XI': Timestamp('2025-02-21 00:00:00'),
 'N225.GI': Timestamp('2025-02-20 00:00:00'),
 '399975.SZ': Timestamp('2025-02-21 00:00:00'),
 '601688.SH': Timestamp('2025-02-21 00:00:00'),
 'HSSCHKY.HI': Timestamp('2025-02-21 00:00:00'),
 'HXC.GI': Timestamp('2025-02-21 00:00:00'),
 'HSHDYI.HI': Timestamp('2025-02-21 00:00:00'),
 'FCHI.GI': Timestamp('2025-02-19 00:00:00'),
 '931787CNY00.CSI': Timestamp('2025-02-21 00:00:00'),
 'H30533.CSI': Timestamp('2025-02-21 00:00:00'),
 'HSIII.HI': Timestamp('2025-02-21 00:00:00'),
 '931791.CSI': Timestamp('2025-02-21 00:00:00'),
 'DJI.GI': Timestamp('2025-02-21 00:00:00'),
 '750108.MI': Timestamp('2025-02-21 00:00:00'),
 'SOX.GI': Timestamp('2025-02-21 00:00:00'),
 '122489.MI': Timestamp('2025-02-21 00:00:00'),
 'HSHKBIO.HI': Timestamp('2025-02-21 00:00:00'),
 'HSHCI.HI': Timestamp('2025-02-21 00:00:00'),
 'RUI.GI': Timestamp('2025-02-21 00:00:00'),
 'SPCLLHCP.SPI': Timestamp('2025-02-21 00:00:00'),
 '707918.MI': Timestamp('2025-02-21 00:00:00'),
 '746059.MI': Timestamp('2025-02-21 00:00:00'),
 '718711L.MI': Timestamp('2025-02-21 00:00:00'),
 '716567.MI': Timestamp('2025-02-21 00:00:00'),
 '704843.MI': Timestamp('2025-02-21 00:00:00'),
 '133333.CSI': Timestamp('2025-02-21 00:00:00'),
 'HSCAIT.HI': Timestamp('2025-02-21 00:00:00'),
 'HSSCHI.HI': Timestamp('2025-02-21 00:00:00'),
 'DJCN88.GI': Timestamp('2025-02-21 00:00:00'),
 '707717L.MI': Timestamp('2025-02-21 00:00:00'),
 'HSSSHID.HI': Timestamp('2025-02-21 00:00:00'),
 '302400.MI': Timestamp('2025-02-21 00:00:00'),
 'HSSSCHD.HI': Timestamp('2025-02-21 00:00:00'),
 'HSSI.HI': Timestamp('2025-02-21 00:00:00'),
 'CES300.CSI': Timestamp('2025-02-21 00:00:00'),
 'HSCGSI.HI': Timestamp('2025-02-21 00:00:00'),
 'HSSCT.HI': Timestamp('2025-02-21 00:00:00'),
 'HSMI.HI': Timestamp('2025-02-21 00:00:00'),
 'HSSCNE.HI': Timestamp('2025-02-21 00:00:00'),
 'HSHYLV.HI': Timestamp('2025-02-21 00:00:00'),
 'CESFHY.CSI': Timestamp('2025-02-21 00:00:00'),
 'GPCCH003.FI': Timestamp('2025-02-21 00:00:00'),
 'HSCSOE.HI': Timestamp('2025-02-21 00:00:00'),
 'HSMCHYI.HI': Timestamp('2025-02-21 00:00:00'),
 'HSSCSOY.HI': Timestamp('2025-02-21 00:00:00'),
 'HSHK35.HI': Timestamp('2025-02-21 00:00:00'),
 'HSBBAC.HI': Timestamp('2025-02-21 00:00:00'),
 'HSCEI.HI': Timestamp('2025-02-21 00:00:00'),
 'HSINH.HI': Timestamp('2025-02-21 00:00:00'),
 'SPHCMSHP.SPI': Timestamp('2025-02-21 00:00:00'),
 'CES100.CSI': Timestamp('2025-02-21 00:00:00'),
 'SPXEWTR.SPI': Timestamp('2025-02-21 00:00:00'),
 'SPTR500N.SPI': Timestamp('2025-02-21 00:00:00'),
 'S5INFT.SPI': Timestamp('2025-02-21 00:00:00'),
 'HSISUI.HI': Timestamp('2025-02-21 00:00:00'),
 'HSIESGS.HI': Timestamp('2025-02-21 00:00:00'),
 'HSFML25.HI': Timestamp('2025-02-21 00:00:00'),
 '990001.CSI': Timestamp('2025-02-21 00:00:00'),
 '716567.CSI': Timestamp('2025-02-21 00:00:00')}

22.19155531574851