In [115]:
import pandas as pd
import numpy as np
import datetime
import json
import os
from IPython.display import display_html
from IPython.display import HTML
import csv

In [116]:
def display_horizontal(*args):
    html_str = ''
    for df in args:
        html_str += df.to_html()
    display_html(
        html_str.replace('table','table style="display:inline;margin-right:50px"'), 
        raw=True
    )

In [117]:
with open("INDEX_START.json", "r", encoding="utf-8") as f:
    INDEX_START = json.load(f)
    
with open("INDEX_NAME.json", 'r', encoding = 'utf-8') as f:
    INDEX_NAME = json.load(f)

In [118]:
df = pd.read_csv("A股指数.csv")
a_share_dict = dict(zip(df["Ticker"], df["Name"]))

df = pd.read_csv("海外指数.csv")
other_market_dict = dict(zip(df["Ticker"], df["Name"]))

print(len(a_share_dict), len(other_market_dict))

333 57

In [119]:
INDEX_DATA = {}

for ticker in INDEX_START:
    path = f"Data/{ticker}.csv"
    
    if os.path.isfile(path): 
        data = pd.read_csv(path, index_col = 0, parse_dates = True)
        data.index = pd.to_datetime(data.index, format="%Y-%m-%d", errors='coerce')
        data.index = data.index.date
        INDEX_DATA[ticker] = data.copy(deep = True)

In [120]:
UNIVERSE_A = {}
UNIVERSE_O = {}
target_dates = {}

for ticker in INDEX_DATA:
    if ticker in a_share_dict:
        target_dates[ticker] = INDEX_DATA[ticker].index[-1]
        UNIVERSE_A[ticker] = INDEX_DATA[ticker]

    elif ticker in other_market_dict:
        target_dates[ticker] = INDEX_DATA[ticker].index[-1]
        UNIVERSE_O[ticker] = INDEX_DATA[ticker]

In [121]:
print(f"Assets under Analysis: {len(UNIVERSE_A)}  {len(UNIVERSE_O)}")
print(f"Total Assets: {len(INDEX_DATA)}")

Assets under Analysis: 73  35
Total Assets: 186

In [122]:
n = 0
for ticker in other_market_dict:
    if ticker in INDEX_DATA:
        n += 1

n

39

## Z Score Calculation

In [126]:
UNIVERSE = UNIVERSE_A
Z_PE_TTM = {}
Z_DIVIDENDYIELD = {}
years = 5
duration = years * 250

for ticker in UNIVERSE:
    target_date = target_dates[ticker]
    if len(UNIVERSE[ticker]) < duration:
        continue
    
    # PE TTM 分位值
    sample_data = UNIVERSE[ticker]['PE_TTM'].loc[:target_date].iloc[-duration:]
    assert len(sample_data) == duration
    
    mean = sample_data.mean()
    std = sample_data.std()
    
    Z = (UNIVERSE[ticker].loc[target_date, "PE_TTM"] - mean) / std
    
    Z_PE_TTM[ticker] = Z
    
    
    # 股息率 分位值
    sample_data = UNIVERSE[ticker]['DIVIDENDYIELD2'].loc[:target_date].iloc[-duration:]
    assert len(sample_data) == duration
    
    mean = sample_data.mean()
    std = sample_data.std()
    
    Z = (UNIVERSE[ticker].loc[target_date, 'DIVIDENDYIELD2'] - mean) / std
    
    Z_DIVIDENDYIELD[ticker] = Z

In [127]:
display_number = 20

df_Z_PE_TTM = pd.DataFrame(list(Z_PE_TTM.items()), columns=['Ticker', '市盈率'])
df_Z_DIVIDENDYIELD = pd.DataFrame(list(Z_DIVIDENDYIELD.items()), columns=['Ticker', '股息率'])

# Sort the dataframes
df_Z_PE_TTM_sorted = df_Z_PE_TTM.sort_values(by='市盈率', ascending=True)
df_Z_DIVIDENDYIELD_sorted = df_Z_DIVIDENDYIELD.sort_values(by='股息率', ascending=False)

# Display the top 10 sorted rows
top_Z_PE_TTM = df_Z_PE_TTM_sorted.head(display_number).copy()
top_Z_DIVIDENDYIELD = df_Z_DIVIDENDYIELD_sorted.head(display_number).copy()

top_Z_PE_TTM.loc[:, "指数名称"] = top_Z_PE_TTM["Ticker"].map(INDEX_NAME)
top_Z_PE_TTM = top_Z_PE_TTM[["Ticker", "指数名称", "市盈率"]]

top_Z_DIVIDENDYIELD.loc[:, "指数名称"] = top_Z_DIVIDENDYIELD["Ticker"].map(INDEX_NAME)
top_Z_DIVIDENDYIELD = top_Z_DIVIDENDYIELD[["Ticker", "指数名称", "股息率"]]

In [128]:
print()
print("A股")
print(f"{INDEX_DATA['000300.SH'].index[-1].strftime('%Y-%m-%d')}")
print(f"{years}年")
display_horizontal(top_Z_PE_TTM, top_Z_DIVIDENDYIELD)
print()

A股
2025-05-15
5年

,Ticker,指数名称,市盈率
9,399812.SZ,养老产业,-1.681620
37,h30035.CSI,300非银,-1.521051
58,399966.SZ,中证800证保,-1.510972
47,931068.CSI,消费龙头,-1.264988
45,931139.CSI,CS消费50,-1.193538
50,930653.CSI,CS食品饮,-1.188510
10,000815.CSI,细分食品,-1.153720
7,707717L.MI,MSCI中国A股质量,-1.070096
46,931079.CSI,5G通信,-0.999484
49,931008.CSI,汽车指数,-0.895608
12,931238.CSI,SSH黄金股票,-0.810291
1,399814.SZ,农业,-0.771888
0,000913.SH,医药,-0.753519
14,000811.CSI,细分有色,-0.732816
39,931892.CSI,有色矿业,-0.732203
19,930997.CSI,新能源车,-0.705562
11,000814.SH,细分医药,-0.684165
25,931406.CSI,5G 50,-0.655774
5,399975.SZ,证券,-0.624664
27,930598.CSI,稀土产业,-0.560403
,Ticker,指数名称,股息率
62,000806.CSI,消费服务,2.014408
33,000056.SH,上证国企,1.937172
10,000815.CSI,细分食品,1.925257
50,930653.CSI,CS食品饮,1.918336
47,931068.CSI,消费龙头,1.908635
15,000901.SH,小康指数,1.886528
11,000814.SH,细分医药,1.874829
6,718711L.MI,MSCI中国A股人民币,1.838929
2,000300.SH,沪深300,1.786052
45,931139.CSI,CS消费50,1.742131
7,707717L.MI,MSCI中国A股质量,1.692560
48,931009.CSI,建筑材料,1.688243
0,000913.SH,医药,1.684390
59,000992.SH,金融地产,1.654458
46,931079.CSI,5G通信,1.644613
18,000812.CSI,细分机械,1.588966
60,000934.SH,800金地,1.577981
44,931140.CSI,医药50,1.575937
17,000827.SH,中证环保,1.548163
42,931380.CSI,科技50,1.542167

In [141]:
UNIVERSE = UNIVERSE_O
Z_PE_TTM = {}
Z_DIVIDENDYIELD = {}
years = 1
duration = years * 252

for ticker in UNIVERSE:
    target_date = target_dates[ticker]
    if len(UNIVERSE[ticker]) < duration:
        continue
    
    # PE TTM 分位值
    sample_data = UNIVERSE[ticker]['PE_TTM'].loc[:target_date].iloc[-duration:]
    sample_data.dropna(inplace = True)
    assert len(sample_data) == duration
    
    mean = sample_data.mean()
    std = sample_data.std()
    
    Z = (UNIVERSE[ticker].loc[target_date, "PE_TTM"] - mean) / std
    
    Z_PE_TTM[ticker] = Z
    
    
    # 股息率 分位值
    sample_data = UNIVERSE[ticker]['DIVIDENDYIELD2'].loc[:target_date].iloc[-duration:]
    sample_data.dropna(inplace = True)
    assert len(sample_data) == duration
    
    mean = sample_data.mean()
    std = sample_data.std()
    
    Z = (UNIVERSE[ticker].loc[target_date, 'DIVIDENDYIELD2'] - mean) / std
    
    Z_DIVIDENDYIELD[ticker] = Z

C:\Users\Bill Yin\AppData\Local\Temp\ipykernel_35412\379741716.py:20: RuntimeWarning: invalid value encountered in scalar divide
  Z = (UNIVERSE[ticker].loc[target_date, "PE_TTM"] - mean) / std
C:\Users\Bill Yin\AppData\Local\Temp\ipykernel_35412\379741716.py:33: RuntimeWarning: invalid value encountered in scalar divide
  Z = (UNIVERSE[ticker].loc[target_date, 'DIVIDENDYIELD2'] - mean) / std

In [142]:
display_number = 20

df_Z_PE_TTM = pd.DataFrame(list(Z_PE_TTM.items()), columns=['Ticker', '市盈率'])
df_Z_DIVIDENDYIELD = pd.DataFrame(list(Z_DIVIDENDYIELD.items()), columns=['Ticker', '股息率'])

# Sort the dataframes
df_Z_PE_TTM_sorted = df_Z_PE_TTM.sort_values(by='市盈率', ascending=True)
df_Z_DIVIDENDYIELD_sorted = df_Z_DIVIDENDYIELD.sort_values(by='股息率', ascending=False)

# Display the top 10 sorted rows
top_Z_PE_TTM = df_Z_PE_TTM_sorted.head(display_number).copy()
top_Z_DIVIDENDYIELD = df_Z_DIVIDENDYIELD_sorted.head(display_number).copy()

top_Z_PE_TTM.loc[:, "指数名称"] = top_Z_PE_TTM["Ticker"].map(INDEX_NAME)
top_Z_PE_TTM = top_Z_PE_TTM[["Ticker", "指数名称", "市盈率"]]

top_Z_DIVIDENDYIELD.loc[:, "指数名称"] = top_Z_DIVIDENDYIELD["Ticker"].map(INDEX_NAME)
top_Z_DIVIDENDYIELD = top_Z_DIVIDENDYIELD[["Ticker", "指数名称", "股息率"]]

In [143]:
print()
print("海外")
print(f"{INDEX_DATA['000300.SH'].index[-1].strftime('%Y-%m-%d')}")
print(f"{years}年")
display_horizontal(top_Z_PE_TTM, top_Z_DIVIDENDYIELD)
print()

海外
2025-05-15
1年

,Ticker,指数名称,市盈率
10,931787CNY00.CSI,港股创新药,-1.359463
12,750108.MI,美国50,-1.084318
0,NDX.GI,纳斯达克指数,-0.847095
7,N225.GI,日经225,-0.827758
5,NDXTMC.GI,纳指科技,-0.819942
31,987008.CNI,港股通科技30,-0.818967
24,SPTR500N.SPI,标普500,-0.658269
23,SPXEWTR.SPI,标普500等权,-0.658269
1,SPX.GI,标普500南方,-0.656705
27,931024.CSI,港股非银,-0.616471
13,SOX.GI,费城半导体,-0.595322
34,TPX.GI,日本东证指数,-0.487503
15,RUI.GI,罗素1000,-0.464621
4,HSTECH.HI,恒生科技基金,-0.407112
29,930709.CSI,香港证券,-0.406151
8,HXC.GI,纳斯达克中国金龙,-0.327119
26,930604.CSI,中概互联,-0.261283
11,DJI.GI,道琼斯,-0.190387
25,S5INFT.SPI,标普500信息科技,-0.046410
28,931454.CSI,港股消费易方达,0.004293
,Ticker,指数名称,股息率
32,h11146.CSI,港股通金融,2.243090
18,HSCSOE.HI,恒生央企,1.898929
7,N225.GI,日经225,1.431469
5,NDXTMC.GI,纳指科技,1.305778
33,h30106.CSI,港股金融,0.953752
34,TPX.GI,日本东证指数,0.866652
0,NDX.GI,纳斯达克指数,0.463762
25,S5INFT.SPI,标普500信息科技,0.422811
20,HSCEI.HI,恒生中国企业,0.312753
27,931024.CSI,港股非银,0.249458
15,RUI.GI,罗素1000,0.034314
23,SPXEWTR.SPI,标普500等权,0.021837
24,SPTR500N.SPI,标普500,0.021837
1,SPX.GI,标普500南方,0.019691
14,122489.MI,MSCI金龙,-0.162947
12,750108.MI,美国50,-0.276186
10,931787CNY00.CSI,港股创新药,-0.432862
13,SOX.GI,费城半导体,-0.487583
16,HSCGSI.HI,恒生消费,-0.518404
31,987008.CNI,港股通科技30,-0.591694

In [114]:
ticker

'000913.SH'

In [110]:
temp = INDEX_DATA[ticker]

In [111]:
temp = temp[~temp.index.duplicated(keep = "last")]

In [113]:
temp.tail()

               PE_TTM  DIVIDENDYIELD2      CLOSE
2025-05-09  28.068100          1.9990  7848.4305
2025-05-12  27.993900          1.8358  7818.1952
2025-05-13  28.240000          1.8197  7891.3630
2025-05-14  28.418400          1.8083  7959.5245
2025-05-15  28.409901          1.8086  7968.7475