In [1]:
import pandas as pd
import numpy as np
import datetime
import json
import os

In [21]:
with open("INDEX_START.json", "r", encoding="utf-8") as f:
    INDEX_START = json.load(f)
    
with open("INDEX_NAME.json", 'r', encoding = 'utf-8') as f:
    INDEX_NAME = json.load(f)

In [8]:
INDEX_DATA = {}

for ticker in INDEX_START:
    path = f"Data/{ticker}.csv"
    
    if os.path.isfile(path): 
        data = pd.read_csv(path, index_col = 0, parse_dates = True)
        INDEX_DATA[ticker] = data.copy(deep = True)
        
len(INDEX_DATA)

45

In [9]:
UNIVERSE = {}

for ticker in INDEX_DATA:
    if datetime.datetime(2025, 2, 18) in INDEX_DATA[ticker].index:
        UNIVERSE[ticker] = INDEX_DATA[ticker].copy(deep = True)

In [10]:
print(f"Assets under Analysis: {len(UNIVERSE)}")
print(f"Total Assets: {len(INDEX_DATA)}")

Assets under Analysis: 45
Total Assets: 45

## Z Score Calculation

In [11]:
Z_PE_TTM = {}
Z_DIVIDENDYIELD = {}
target_date = datetime.datetime(2025, 2, 18)
duration = 750

for ticker in UNIVERSE:
    if len(UNIVERSE[ticker]) < duration:
        continue
    
    # PE TTM 分位值
    sample_data = UNIVERSE[ticker]['PE_TTM'].loc[:target_date].iloc[-duration:]
    assert len(sample_data) == duration
    
    mean = sample_data.mean()
    std = sample_data.std()
    
    Z = (UNIVERSE[ticker].loc[target_date, "PE_TTM"] - mean) / std
    
    Z_PE_TTM[ticker] = Z
    
    
    # 股息率 分位值
    sample_data = UNIVERSE[ticker]['DIVIDENDYIELD2'].loc[:target_date].iloc[-duration:]
    assert len(sample_data) == duration
    
    mean = sample_data.mean()
    std = sample_data.std()
    
    Z = (UNIVERSE[ticker].loc[target_date, 'DIVIDENDYIELD2'] - mean) / std
    
    Z_DIVIDENDYIELD[ticker] = Z

In [27]:
df_Z_PE_TTM = pd.DataFrame(list(Z_PE_TTM.items()), columns=['Ticker', 'PE_TTM'])
df_Z_DIVIDENDYIELD = pd.DataFrame(list(Z_DIVIDENDYIELD.items()), columns=['Ticker', 'DIVIDENDYIELD'])

# Sort the dataframes
df_Z_PE_TTM_sorted = df_Z_PE_TTM.sort_values(by='PE_TTM', ascending=True)
df_Z_DIVIDENDYIELD_sorted = df_Z_DIVIDENDYIELD.sort_values(by='DIVIDENDYIELD', ascending=False)

# Display the top 10 sorted rows
top_Z_PE_TTM = df_Z_PE_TTM_sorted.head(15)
top_Z_DIVIDENDYIELD = df_Z_DIVIDENDYIELD_sorted.head(15)

top_Z_PE_TTM.loc[:, "Name"] = top_Z_PE_TTM["Ticker"].map(INDEX_NAME)
top_Z_PE_TTM = top_Z_PE_TTM[["Ticker", "Name", "PE_TTM"]]

top_Z_DIVIDENDYIELD.loc[:, "Name"] = top_Z_DIVIDENDYIELD["Ticker"].map(INDEX_NAME)
top_Z_DIVIDENDYIELD = top_Z_DIVIDENDYIELD[["Ticker", "Name", "DIVIDENDYIELD"]]

C:\Users\Bill Yin\AppData\Local\Temp\ipykernel_34376\2971009115.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_Z_PE_TTM.loc[:, "Name"] = top_Z_PE_TTM["Ticker"].map(INDEX_NAME)
C:\Users\Bill Yin\AppData\Local\Temp\ipykernel_34376\2971009115.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_Z_DIVIDENDYIELD.loc[:, "Name"] = top_Z_DIVIDENDYIELD["Ticker"].map(INDEX_NAME)

In [28]:
top_Z_PE_TTM

             Ticker         Name    PE_TTM
2         000913.SH           医药 -0.883478
36       707717L.MI   MSCI中国A股质量 -0.722872
13        601688.SH         华泰证券 -0.664856
3         399814.SZ           农业 -0.641574
18       H30533.CSI        中概互联网 -0.612299
24       HSHKBIO.HI       恒生生物科技 -0.492024
34        HSSCHI.HI      恒生港股通医疗 -0.478001
6         DJSOEP.GI      道琼斯美国石油 -0.462264
7         HSTECH.HI         恒生科技 -0.441370
39          HSSI.HI        恒生小型股 -0.408341
19         HSIII.HI        恒生互联网 -0.377135
25         HSHCI.HI       恒生医疗保健 -0.352537
17  931787CNY00.CSI        港股创新药 -0.087823
28        746059.MI  MSCI中国A50互联  0.357385
31        704843.MI   MSCI中国A股国际  0.395814

In [29]:
top_Z_DIVIDENDYIELD

        Ticker            Name  DIVIDENDYIELD
34   HSSCHI.HI         恒生港股通医疗       2.420695
25    HSHCI.HI          恒生医疗保健       2.265480
2    000913.SH              医药       1.860275
27   707918.MI  MSCI中国A股低波(美元)       1.846699
29  718711L.MI     MSCI中国A股人民币       1.792903
30   716567.MI  MSCI中国A股国际(美元)       1.792712
31   704843.MI      MSCI中国A股国际       1.791167
28   746059.MI     MSCI中国A50互联       1.720142
32  133333.CSI        MSCI中国A股       1.708998
20  931791.CSI           中韩半导体       1.670034
4    000300.SH           沪深300       1.558909
33   HSCAIT.HI          恒生A股龙头       1.514643
3    399814.SZ              农业       1.446552
10   830009.XI         富时中国A50       1.401773
37  HSSSHID.HI         恒生创新药50       1.376563

In [ ]:
target_date = datetime.datetime(2025, 2, 13)
sample_data = CSI300['PE_TTM'].loc[:target_date].iloc[-2500:]

In [ ]:
sample_data

In [ ]:
INDEX_NAME